### ISSUE TITLE
Duplicated offenders on hawkeye report

### ISSUE THREAD

**Issue by Bonifacio2** [Stono/hawkeye#12]
Sometimes hawkeye returns more than one entry for the same offender. For instance:

```
level   description                                       offender         mitigation                            
------  ------------------------------------------------  ---------------  --------------------------------------
high    Regular Expression Denial of Service              tough-cookie     https://nodesecurity.io/advisories/525
high    Regular Expression Denial of Service              tough-cookie     https://nodesecurity.io/advisories/525
high    Regular Expression Denial of Service              tough-cookie     https://nodesecurity.io/advisories/525
```

**Comment by Stono** [comment]
Hola @Bonifacio2 
Looking into this more, it isn't actually duplicated.
Basically the "offender" is only showing the top level dependency, what's actually happening there is tough-cookie is being used as a dependency in multiple child dependencies in the dependency tree, so it's actually vulnerable in three places!

In this case:
  - npm-check-updates@2.12.1 -> npm@3.10.10 -> node-gyp@3.4.0 -> request@2.82.0 -> tough-cookie@2.3.2
  - request@2.82.0 -> tough-cookie@2.3.2
  - npm-check-updates@2.12.1 -> npm@3.10.10 -> request@2.75.0 -> tough-cookie@2.3.2

We don't show that complete path in the summary output because the paths are too long, but I appreciate that it then doesn't give you enough context.

The full paths can be see on the json output writer, or on the hawkeye.website.

I'm open to suggestions for how we could maybe display this better, perhaps we could do "tough-cookie *" where the "*" indicates a sub-dependency rather than top level?

**Comment by Stono** [comment]
Closing as this isn't actually a bug and no other suggestions have been brought forward :)
