### ISSUE TITLE
File count limit option

### ISSUE THREAD

**Issue by scooterhanson** [Stono/hawkeye#27]
Can we make the file count limit configurable at runtime or via the rc file?

**Comment by jackpetraitis** [comment]
Yeah, this should be configurable by the rc file too in my opinion.
Here we can see it only checks for these options in the rc file:
[see it here](https://i.imgur.com/oAJDQZM.png)

Perhaps we can add fileLimit to that list...

**Comment by felixhammerl** [comment]
I don't see a reason why we need the file limit, apart from the SaaS version @Stono had up for a while. If someone really needs it, they can add it via: https://github.com/Stono/hawkeye/pull/58

Otherwise, I removed the option as it really seems pointless to have it.

**Comment by Stono** [comment]
I agree 👌

On 29 Sep 2018 6:37 pm, "Felix Hammerl" <notifications@github.com> wrote:

I don't see a reason why we need the file limit, apart from the SaaS
version @Stono <https://github.com/Stono> had up for a while. If someone
really needs it, they can add it via: #58
<https://github.com/Stono/hawkeye/pull/58>

Otherwise, I removed the option as it really seems pointless to have it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Stono/hawkeye/issues/27#issuecomment-425662512>, or mute
the thread
